title: Sara Pesavento
subtitle: Rdvark Blog
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a Jekyll Theme Built For Developers

url: "https://spesavento.github.io/" # the base hostname & protocol for your site, e.g. https://example.github.io
# baseurl: "/tree/master/assets/img" # the subpath of your site, e.g. /blog

urls:
    - text:
      url: /about 
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Programming
      url: /programming
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Sara Pesavento
author_bio: Programming knowledge includes R, Python, SQL, Tableau, SAS and other data analysis tools.
author_email: "sarapesavento@gmail.com"
author_location: Los Angeles
# author_website_url: "https://www.linkedin.com/in/sara-pesavento-95941811a/"

author_education_details:
              - college_logo: USC.png
                college_name: University of Southern California <br>2020-present
                # college_url: www.usc.com
                college_degree: M.S. Computer Science
                description: GPA NA/4.00
                visibility: true
              - college_logo: ucla.png
                college_name: University of California, Los Angeles <br>2014-2018
                # college_url: http://statistics.ucla.edu
                college_degree: B.S. Statistics
                description: GPA 3.82/4.00
                visibility: true

author_work_experiences:
            - company_name: Warner Bros. Entertainment<br>Mar 2019 - Present • <i>1 yr 1 mo</i>
              company_logo: wb.png
              # company_url: https://google.com
              designation: Sr. Analyst
              description: <ul> <li>Determine forecasting methods, predictor variables and statistical model validation techniques to forecast sales for the supply chain</li> <li>Present data model analysis and justification with business leaders</li> <li>Maintain SQL/SAS/R data sources from internal and external databases</li> <li>Provide cross functional statistical analyses and data mining</li> <li>Data visualization in Tableau</li> </ul>
              visibility: true
            - company_name: Welch Consulting<br>Jul 2018 - Mar 2019 • <i>9 mo</i>
              company_logo: welch.png
              # company_url: https://microsoft.com
              designation: Quantitative Data Analyst
              description: <ul><li>Data mining and analysis of large economic datasets using STATA programming</li><li>Performed programming and statistical analysis for client reports</li></ul>
              visibility: true
            - company_name: Twenty20<br>Apr 2018 - Jun 2018 • <i>3 mo</i>
              company_logo: twenty.png
              # company_url: https://microsoft.com
              designation: Data Analyst Intern
              description: <ul><li>Statistically analyzed growth frameworks and key performance drivers to increase the number of active users for this venture-funded startup</li><li>Tools used included RJ, Amplitude, Excel, Batch, UX design (Balsamiq), A/B testing</li></ul>
              visibility: true
            - company_name: UCLA Brain Mapping Center<br>Sep 2017 - Jun 2018 • <i>10 mo</i>
              company_logo: brain.png
              # company_url: https://microsoft.com
              designation: Data Scientist
              description: <ul><li>Developed and tested software in R for analyzing brain imaging data</li><li>Performed statistical analysis on MRI data from Brainsuite using Bitbucket (Git), and R </li><li>Explored machine learning tools (Tensorflow) in R for further analyzing brain imaging data</li></ul>
              visibility: true
            - company_name: UCLA Aftercare Research Program<br>Jun 2017 - Sep 2017 • <i>4 mo</i>
              company_logo: semel.png
              # company_url: https://microsoft.com
              designation: Data Analyst
              description: <ul><li>Performed data entry, quality checks and control, and statistical analysis of psychiatric treatment data using SPSS and Excel</li></ul>
              visibility: true

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
# twitter_username: johndoe
github_username:  spesavento
facebook_username: sara.briana.9
linkedin_username: sara-pesavento-95941811a
# behance_username: johndoe
instagram_username: sarapez4
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments using disqus
disqus_shortname: sujay-kundu

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: johndoe@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings

#theme: devlopr
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build